fragment OrderFields on Order {
  id
  name
  createdAt
  cancelledAt
  closedAt
  note
  displayFinancialStatus
  displayFulfillmentStatus
  currentSubtotalPriceSet { shopMoney { amount currencyCode } }
  currentTotalTaxSet { shopMoney { amount currencyCode } }
  currentTotalDiscountsSet { shopMoney { amount currencyCode } }
  totalShippingPriceSet { shopMoney { amount currencyCode } }
  currentTotalPriceSet { shopMoney { amount currencyCode } }
  netPaymentSet { shopMoney { amount currencyCode } }
  customer {
    id
    firstName
    lastName
    defaultEmailAddress {
      emailAddress
    }
    defaultPhoneNumber {
      phoneNumber
    }
  }
  lineItems(first: 40) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ...LineItemFields
    }
  }
}
